### ISSUE TITLE
looks good to me :)

### ISSUE THREAD

**Issue by greggles** [pwolanin/drupal8-security-improvements#1]
You dropped off irc before I got to say it, but this looks good to me. Thanks for presenting on it.

**Comment by pwolanin** [comment]
Thanks - was pretty well received.

On Thu, Aug 13, 2015 at 6:31 PM, Greg Knaddison notifications@github.com
wrote:

> You dropped off irc before I got to say it, but this looks good to me.
> Thanks for presenting on it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pwolanin/drupal8-security-improvements/issues/1.

## 

Peter M. Wolanin, Ph.D.      : Principal Cloud Security Engineer,  Acquia.
Inc.
peter.wolanin@acquia.com : 609-235-6869

**Comment by greggles** [comment]
As an issue I think this is "closed".

Thanks for compiling and presenting this!
